### PR TITLE
fix: modify `script` evaluation for IE11

### LINKED ISSUE #36: Cannot use the script with Internet Explorer 11
Hello,

I can't use this script in InternetExplorer 11 on an Apache HTTP Server.

I get an error when calling the method execScript() from addScripts.js:

module.exports = function(src) {
	if (typeof execScript !== "undefined")
		execScript(src);
	else
		eval.call(null, src);
}

The execScript() method is deprecated in IE 11.

Any solutions to this ?

### LINKED ISSUE #39: CSP does not allow eval
Can we use another way other than calling eval?

This is not good for security reasons

https://github.com/webpack-contrib/script-loader/blob/master/addScript.js#L9

```
addScript.js:9 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


    at eval (<anonymous>)
    at e.exports (addScript.js:9)
    at Object.659 (jquery.mask.js?872b:1)
    at __webpack_require__ (bootstrap 3d71110…:54)
    at Object.869 (vendors.js:32296)
    at __webpack_require__ (bootstrap 3d71110…:54)
    at e.20 (bootstrap 3d71110…:152)
    at bootstrap 3d71110…:152
```

source: https://scotthelme.co.uk/content-security-policy-an-introduction/

### PR DESCRIPTION
**Pull request by markus-wi**
### Pull Request (Notable Changes)

I've moved up the check for `eval` because IE11 still has the `execScript` function, but throws an error when it's called.

The added error handling allows us to gracefuly reject scripts with non compatible code (like ES6 syntax). It would be better if we could transpile with babel before evaluating, but I don't know how we could implement that. There's already a separate issue regarding this feature (See #40).

### Issues

Fixes #36 
Fixes #39 

> Edited by @michael-ciniawsky (Formatting && Fixes #Issue Support)

### CODE REVIEW

File: addScript.js [hunk 1]
```diff
@@ -3,8 +3,15 @@
...
-		execScript(src);
-	else
-		eval.call(null, src);
+	try {
+		if (typeof eval !== "undefined") {
+			eval.call(null, src);
+		} else if (typeof execScript !== "undefined") {
+			execScript(src);
+		} else {
+			// TODO error: no eval function available
```
Comment (evilebottnawi) [inline addScript.js]: Using `Todo` in code is bad practice. How we can solve this problem, what you think?

Comment (markus-wi) [inline addScript.js]: As I mention in the description of my pull request, I don't know how these errors should be handled. We could just log them ( `console.log("no eval function available")` ) or throw them (`throw new Error("no eval function available"), so that they have to be handled outside of the script loader.

Comment (evilebottnawi) [inline addScript.js]: @markus-wi i think `console.log` is good solution.

Comment (markus-wi) [inline addScript.js]: @evilebottnawi ok, I've added the error logging and updated my pull request

File: addScript.js [hunk 2]
```diff
@@ -3,8 +3,15 @@
...
-		execScript(src);
-	else
-		eval.call(null, src);
+	try {
+		if (typeof eval !== "undefined") {
+			eval.call(null, src);
+		} else if (typeof execScript !== "undefined") {
+			execScript(src);
+		} else {
+			console.log("no eval function available");
```
Comment (michael-ciniawsky) [inline addScript.js]: Tnis should throw please

```js
throw new Error('EvaluationError: No eval function available')
```

File: addScript.js [hunk 3]
```diff
@@ -3,8 +3,15 @@
...
+		}
+	} catch (error) {
+		console.log("script evaluation error occurred", error);
```
Comment (michael-ciniawsky) [inline addScript.js]:
```js
console.error('[Script Loader] ', err.message)
```

**Comment by michael-ciniawsky** [comment]
> I've moved up the check for eval **because IE11 still has the execScript function, but throws an error when it's called**

Is the `execScript` still needed, or could it be removed as superseded by `eval/new Function()`? (General Question)

File: addScript.js (hunk 2 above)
Comment (evilebottnawi) [inline addScript.js]: @michael-ciniawsky it can be break execution there `eval` and `execScript` not allowed (CSP). Maybe best output `error` than break execution?

Comment (michael-ciniawsky) [inline addScript.js]: So the `try/catch` is solely for errors within `eval` ?

Comment (markus-wi) [reply addScript.js]: @michael-ciniawsky I've updated my commit accordingly.

**Comment by markus-wi** [comment]
> Is the execScript still needed, or could it be removed as superseded by eval/new Function()? (General Question)

As far as I know, execScript is needed for IE < 11 compatibility

**Comment by TigerC10** [comment]
👍  I just tested this myself and it works great.  Solves the problem beautifully.
